# Generated by Django 3.1.2 on 2020-10-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customerfollowup_intention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfollowup',
            name='intention',
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '2周内报名'), (1, '1个月内报名'), (2, '近期无报名计划'), (3, '已在其它机构报名'), (4, '已报名'), (5, '已拉黑')]),
        ),
    ]
